"""
database/models.py
==================
SQLAlchemy ORM models for the Maveric MiniPilot chatbot system.

This module defines the three core database tables used by the application:

1. DocumentChunk  — stores chunked and embedded content from the Maveric repo
2. ChatSession    — tracks individual user sessions
3. ChatMessage    — stores the full conversation history per session

These models are used by:
- rag_engine/ingest.py     : writes DocumentChunk records during ingestion
- rag_engine/retriever.py  : queries DocumentChunk using pgvector similarity search
- backend/main.py          : reads/writes ChatSession and ChatMessage records

Vector dimensions:
    The embedding column uses 384 dimensions, which corresponds to the output
    size of the 'all-MiniLM-L6-v2' sentence-transformers model used for local
    embedding generation. If you switch to a different embedding model, this
    value must be updated accordingly (e.g. OpenAI text-embedding-3-small = 1536).

Dependencies:
    - SQLAlchemy 2.x         : ORM and schema definition
    - pgvector.sqlalchemy    : Vector column type for PostgreSQL pgvector extension
    - PostgreSQL + pgvector  : Database backend with vector similarity search support
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy.sql import func
from pgvector.sqlalchemy import Vector

Base = declarative_base()
"""
Base class for all SQLAlchemy ORM models in this project.

All model classes inherit from this Base. When `Base.metadata.create_all(engine)`
is called in database/connection.py, SQLAlchemy uses this shared Base to discover
and create all registered tables in the database.
"""
class DocumentChunk(Base):
    """
    Represents a single chunk of text extracted from the Maveric repository,
    along with its vector embedding for semantic similarity search.

    During ingestion (rag_engine/ingest.py), source files from the Maveric repo
    are read, split into overlapping text chunks of ~800 characters, and each
    chunk is embedded using the 'all-MiniLM-L6-v2' sentence-transformers model.
    The resulting 384-dimensional embedding vector is stored alongside the raw
    text content in this table.

    At query time (rag_engine/retriever.py), the user's question is embedded
    using the same model, and a pgvector cosine similarity search is performed
    against all stored embeddings to retrieve the most semantically relevant
    chunks. These chunks are then injected into the LLM prompt as context.

    Table name:
        document_chunks

    Columns:
        id (int, PK):
            Auto-incrementing primary key. Uniquely identifies each chunk.

        source (str, max 500 chars):
            The relative file path of the source file within the Maveric repo.
            Example: 'radp/digital_twin/rf/bayesian/bayesian_engine.py'
            Used to show the user which file the answer was sourced from.

        file_type (str, max 20 chars):
            The file extension of the source file.
            Examples: '.py', '.md', '.yaml', '.json', '.pdf'
            Useful for filtering retrieval by file type if needed in future.

        content (text):
            The raw text content of this chunk. Typically 800 characters with
            150-character overlap with adjacent chunks to preserve context
            across chunk boundaries. This is what gets injected into the LLM
            prompt as retrieved documentation context.

        embedding (Vector(384)):
            A 384-dimensional floating point vector representing the semantic
            meaning of the content field. Generated by the sentence-transformers
            'all-MiniLM-L6-v2' model. Stored as a pgvector column, enabling
            efficient cosine similarity search using the <=> operator in SQL.
            Note: dimension must match the embedding model output size exactly.

        created_at (datetime):
            Timestamp of when this chunk was inserted into the database.
            Automatically set by the database server on insert using now().
            Useful for tracking when the last ingestion was performed.

    Usage example:
        # Writing (in ingest.py)
        db.add(DocumentChunk(
            source="radp/digital_twin/rf/bayesian/bayesian_engine.py",
            file_type=".py",
            content="class BayesianEngine: ...",
            embedding=[0.023, -0.117, ...]  # 384 floats
        ))

        # Reading (in retriever.py via raw SQL with pgvector)
        SELECT source, content, 1 - (embedding <=> :query_vector) AS similarity
        FROM document_chunks
        ORDER BY embedding <=> :query_vector
        LIMIT 4;
    """
    __tablename__ = "document_chunks"

    id         = Column(Integer, primary_key=True, index=True)
    source     = Column(String(500), nullable=False)
    file_type  = Column(String(20))
    content    = Column(Text, nullable=False)
    embedding  = Column(Vector(384))
    created_at = Column(DateTime, server_default=func.now())


class ChatSession(Base):
    """
    Represents a single user conversation session with the Maveric MiniPilot chatbot.

    A session is created the first time a user sends a message with a given
    session_id. Sessions group related ChatMessage records together, allowing
    the chatbot to maintain conversation context across multiple turns within
    the same session.

    In the Streamlit frontend (frontend/app.py), a UUID is generated when the
    app loads and used as the session_id for the duration of that browser session.
    When the user clicks 'Clear chat', the session and all its messages are
    deleted from the database and a new UUID is generated.

    Table name:
        chat_sessions

    Columns:
        id (int, PK):
            Auto-incrementing primary key. Internal database identifier.

        session_id (str, max 100 chars, unique, indexed):
            The external session identifier provided by the client. Typically
            a UUID4 string generated by the Streamlit frontend.
            Example: '3f2a1b4c-8d9e-4f5a-b6c7-1d2e3f4a5b6c'
            Must be unique across all sessions. Indexed for fast lookup.

        created_at (datetime):
            Timestamp of when this session was first created in the database.
            Automatically set by the database server on insert using now().

    Relationships:
        messages (list[ChatMessage]):
            One-to-many relationship to all ChatMessage records belonging to
            this session. Configured with cascade='all, delete-orphan' so that
            when a ChatSession is deleted, all its associated ChatMessage records
            are automatically deleted as well. This prevents orphaned messages
            in the database when a user clears their chat history.

    Usage example:
        # Creating a new session (in backend/main.py)
        session = ChatSession(session_id="3f2a1b4c-...")
        db.add(session)
        db.commit()

        # Looking up an existing session
        session = db.query(ChatSession).filter_by(session_id="3f2a1b4c-...").first()

        # Deleting a session and all its messages (cascade)
        db.delete(session)
        db.commit()
    """
    __tablename__ = "chat_sessions"

    id         = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(100), unique=True, nullable=False, index=True)
    created_at = Column(DateTime, server_default=func.now())
    messages   = relationship("ChatMessage", back_populates="session",
                              cascade="all, delete-orphan")


class ChatMessage(Base):
    """
    Represents a single message in a conversation, either from the user
    or from the MiniPilot assistant.

    ChatMessage records are created in pairs — one user message and one
    assistant message — every time the /chat endpoint is called successfully.
    They are associated with a ChatSession via the session_id foreign key.

    When building the LLM prompt in backend/main.py, the last 10 messages
    for the session are retrieved in chronological order and included in the
    messages array sent to the Groq API. This gives the LLM awareness of
    the recent conversation history, enabling context-aware follow-up answers.

    Table name:
        chat_messages

    Columns:
        id (int, PK):
            Auto-incrementing primary key. Uniquely identifies each message.

        session_id (str, FK → chat_sessions.session_id):
            Foreign key linking this message to its parent ChatSession.
            Indexed for fast retrieval of all messages belonging to a session.
            On session deletion, all related messages are cascade-deleted.

        role (str, max 20 chars):
            Indicates who sent this message. One of two values:
            - 'user'      : a message typed by the human user
            - 'assistant' : a response generated by the Groq LLM
            This maps directly to the role field in the OpenAI/Groq chat
            completions API message format.

        content (text):
            The full text content of the message. For user messages, this is
            exactly what the user typed. For assistant messages, this is the
            full response returned by the Groq LLaMA3 model.

        created_at (datetime):
            Timestamp of when this message was stored in the database.
            Automatically set by the database server on insert using now().
            Used to retrieve messages in chronological order when building
            the conversation history for the LLM prompt.

    Relationships:
        session (ChatSession):
            Many-to-one relationship back to the parent ChatSession.
            Allows navigation from a message to its session if needed.

    Usage example:
        # Saving a user + assistant message pair (in backend/main.py)
        db.add(ChatMessage(session_id="3f2a1b4c-...", role="user",
                           content="What is the Digital Twin module?"))
        db.add(ChatMessage(session_id="3f2a1b4c-...", role="assistant",
                           content="The Digital Twin module is responsible for..."))
        db.commit()

        # Retrieving last 10 messages for LLM context
        messages = (
            db.query(ChatMessage)
            .filter_by(session_id="3f2a1b4c-...")
            .order_by(ChatMessage.created_at.desc())
            .limit(10)
            .all()
        )
        # Reverse to get chronological order
        history = [{"role": m.role, "content": m.content} for m in reversed(messages)]
    """
    __tablename__ = "chat_messages"

    id         = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(100), ForeignKey("chat_sessions.session_id"), nullable=False)
    role       = Column(String(20), nullable=False)
    content    = Column(Text, nullable=False)
    created_at = Column(DateTime, server_default=func.now())
    session    = relationship("ChatSession", back_populates="messages")